# Generated by Django 2.1 on 2018-08-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='openMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(default=1)),
                ('board', models.CharField(default='', max_length=2000)),
                ('scoreboard', models.CharField(default='0,0,0,0,0,0,0,0,0', max_length=2000)),
                ('playersTurn', models.IntegerField(default=1, max_length=2)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee_game_id', to='login_reg.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_game_id', to='login_reg.User')),
            ],
        ),
    ]
