# Generated by Django 2.1 on 2018-08-22 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openmatches',
            old_name='diffiliculty',
            new_name='difficulty',
        ),
    ]
