# Generated by Django 2.1 on 2018-08-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180822_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmatches',
            name='scoreboard',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
