# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-21 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_openmatches'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmatches',
            name='diffiliculty',
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
