# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-22 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_openmatches_diffiliculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmatches',
            name='board',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='openmatches',
            name='diffiliculty',
            field=models.IntegerField(default=1),
        ),
    ]
