# Generated by Django 2.1 on 2018-08-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_openmatches_scoreboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmatches',
            name='scoreboard',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0', max_length=2000),
        ),
    ]
