# Generated by Django 2.1 on 2018-08-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180823_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmatches',
            name='playersTurn',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
