# Generated by Django 2.1 on 2018-08-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_openmatches_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openmatches',
            name='winner',
        ),
    ]
